inherit_from: .rubocop_todo.yml

require:
  - solidus_dev_support/rubocop

plugins:
  - rubocop-rspec
  - rubocop-rails

inherit_gem:
  solidus_dev_support: .rubocop.yml

AllCops:
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*
